export const notionToFirestore = {
    Allergies: "Allergies",
    "Last Name": "lastName",
    "GitHub URL": "githubUrl",
    "Agreed To Receive Emails From MLH": "agreedToReceiveEmailsFromMLH",
    "In a few sentences, what up-and-coming or revolutionizing technology are you most excited about?":
        "revolutionizingTechnology",
    Gender: "gender",
    Sexuality: "sexuality",
    "LinkedIn URL": "linkedinUrl",
    City: "city",
    "Other Website URL": "personalWebsiteUrl",
    "Why do you want to be a volunteer at HawkHacks?": "reasonToBeVolunteer",
    "Country of Residence": "countryOfResidence",
    "Agreed To HawkHacks CoC": "agreedToHawkHacksCoC",
    Diets: "diets",
    Major: "major",
    School: "school",
    "Agreed To MLH CoC": "agreedToMLHCoC",
    "Applicant ID": "applicantId",
    "Sponsor/General Resume": "generalResumeRef",
    Email: "email",
    "Why do you want to participate at HawkHacks?": "reasonToBeInHawkHacks",
    "Submission Date": "timestamp",
    Ethnicity: "race",
    "Agreed To WLU CoC": "agreedToWLUCoC",
    "Have you mentored at previous hackathons before?": "mentorExperience",
    "Why do you want to be a mentor at HawkHacks?": "reasonToBeMentor",
    "Have you volunteered at large-scale events before?": "referralSources",
    "Level of Study": "levelOfStudy",
    "First Name": "firstName",
    Discord: "discord",
    Phone: "phone",
    "Programming Languages": "programmingLanguages",
    "Describe Salt": "describeSalt",
    "Agreet To MLH ToC And Privacy Policy": "agreetToMLHToCAndPrivacyPolicy",
    Pronouns: "pronouns",
    "How many Hackathons have you attended as a participant in the past?":
        "hackathonExperience",
    Interests: "interests",
    Age: "age",
    "Mentor Resume": "mentorResumeRef",
    "In a couple of sentences, what would you be most excited about helping out with at HawkHacks and why?":
        "excitedToVolunteerFor",
    "Participating As": "participatingAs",
    "Doc ID": "docId",
};
