export const schedule = [
    {
        title: "Registration",
        startTime: "6:00PM",
        endTime: "11:00PM",
        startDate: "May 17",
        endDate: "May 17",
        location: "Atrium Welcome Booth",
        type: "Important",
        description: "",
    },
    {
        title: "Opening Ceremony",
        startTime: "7:45PM",
        endTime: "9:20PM",
        startDate: "May 17",
        endDate: "May 17",
        location: "LH 1001",
        type: "Important",
        description:
            "Doors open 7:30, doors “officially” open 7:45, and ceremony starts 8",
    },
    {
        title: "Friday Dinner - Ennio's Pasta House",
        startTime: "9:20PM",
        endTime: "11:00PM",
        startDate: "May 17",
        endDate: "May 17",
        location: "Atrium Food Table",
        type: "Food",
        description: "",
    },
    {
        title: "Minecraft Build Competition",
        startTime: "9:20PM",
        endTime: "11:49PM",
        startDate: "May 17",
        endDate: "May 18",
        location: "",
        type: "Game/Chill",
        description: "Plots of land that cannot be destroyed by other players",
    },
    {
        title: "Hacking Period",
        startTime: "9:20PM",
        endTime: "11:49PM",
        startDate: "May 17",
        endDate: "May 18",
        location: "",
        type: "Important",
        description: "",
    },
    {
        title: "Intro to Blockchain/Web3 w/NEAR Toronto. AVAX MTL, CookBook, and METIS",
        startTime: "9:45PM",
        endTime: "10:45PM",
        startDate: "May 17",
        endDate: "May 17",
        location: "LH 1001",
        type: "Workshop",
        description:
            "After 25 intermission for food, another 1h block to finish what they would cover in the workshop, possibly a demo to add on to the high level information during the keynotes",
    },
    {
        title: "Smash Tournament",
        startTime: "11:00PM",
        endTime: "11:59PM",
        startDate: "May 17",
        endDate: "May 17",
        location: "LH 3098",
        type: "Game/Chill",
        description:
            "https://challonge.com/tournament/bracket_generator, gonna do 1 vs 1 tournaments and would like to run this event longer. need a switch and 2 controllers. Gonna use the linked tournament bracket, and may have a losers bracket depending on what we decide",
    },
    {
        title: "Saturday Breakfast",
        startTime: "9:00AM",
        endTime: "10:00PM",
        startDate: "May 18",
        endDate: "May 18",
        location: "Atrium Food Table",
        type: "Food",
        description: "Sponsored by NEAR",
    },
    {
        title: "Networking 101 w/Ian Schwartz",
        startTime: "11:30AM",
        endTime: "12:30PM",
        startDate: "May 18",
        endDate: "May 18",
        location: "LH 1009",
        type: "Workshop",
        description: "",
    },
    {
        title: "Board Game Room",
        startTime: "12:00PM",
        endTime: "9:00PM",
        startDate: "May 18",
        endDate: "May 18",
        location: "LH 3101",
        type: "Game/Chill",
        description: "",
    },
    {
        title: "Sponsor Booths",
        startTime: "12:00PM",
        endTime: "6:00PM",
        startDate: "May 18",
        endDate: "May 18",
        location: "Atrium",
        type: "Networking",
        description: "",
    },
    {
        title: "Saturday Lunch - Smoke's Poutinerie & Sweet Lou's Cookies",
        startTime: "1:00PM",
        endTime: "2:00PM",
        startDate: "May 18",
        endDate: "May 18",
        location: "Atrium Food Table",
        type: "Food",
        description: "",
    },
    {
        title: "Machine Learning & Mental Health w/Nathan Laundry",
        startTime: "2:00PM",
        endTime: "3:00PM",
        startDate: "May 18",
        endDate: "May 18",
        location: "TBD",
        type: "Workshop",
        description: "",
    },
    {
        title: "!Light MLH Event",
        startTime: "3:00PM",
        endTime: "4:00PM",
        startDate: "May 18",
        endDate: "May 18",
        location: "TBD",
        type: "Game/Chill",
        description: "",
    },
    {
        title: "Saturday Dinner - Domino's Pizza",
        startTime: "7:00PM",
        endTime: "8:00PM",
        startDate: "May 18",
        endDate: "May 18",
        location: "Atrium Food Table",
        type: "Food",
        description: "",
    },
    {
        title: "Fast Typing Competition",
        startTime: "8:30PM",
        endTime: "9:00PM",
        startDate: "May 18",
        endDate: "May 18",
        location: "TBD",
        type: "Game/Chill",
        description: "",
    },
    {
        title: "Sunday Brunch",
        startTime: "10:00AM",
        endTime: "1:00PM",
        startDate: "May 19",
        endDate: "May 19",
        location: "Atrium Food Table",
        type: "Food",
        description: "",
    },
    {
        title: "Judging Period/Project Presentations",
        startTime: "11:00AM",
        endTime: "3:00PM",
        startDate: "May 19",
        endDate: "May 19",
        location: "LH 1001",
        type: "Important",
        description: "",
    },
    {
        title: "Closing Ceremony",
        startTime: "4:00PM",
        endTime: "5:00PM",
        startDate: "May 19",
        endDate: "May 19",
        location: "LH 1001",
        type: "Important",
        description: "",
    },
];

export default schedule;
